<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SubmitAdmission.Shared</AssemblyName>
    <RootNamespace>SubmitAdmission.Shared</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Zlink.Framework/Zlink.Framework.csproj" />
  </ItemGroup>
</Project>
