namespace Zlink.Framework.Runtime.Spots;

internal static class ZLinkSpotReplyEnvelope
{
    public static IReadOnlyList<Message> EncodeActorJoinReplyParts(
        string channelName,
        string messageName,
        object? reply,
        Type? replyType,
        ZLinkCodecRegistryBuilder? codecs = null)
    {
        var replyHeader = new ZLinkEnvelopeHeader(
            ZLinkMessageKind.Command,
            channelName,
            string.Empty,
            ZLinkEnvelopeCodec.DefaultContentType,
            null,
            null,
            null,
            null,
            null);
        return ZLinkEnvelopeCodec.EncodeParts(replyHeader, reply, replyType, codecs);
    }

    public static IReadOnlyList<Message> EncodeResponseParts(
        string channelName,
        string messageName,
        string? correlationId,
        object? reply,
        Type? replyType,
        ZLinkCodecRegistryBuilder? codecs = null)
    {
        var replyHeader = new ZLinkEnvelopeHeader(
            ZLinkMessageKind.Response,
            channelName,
            messageName,
            ZLinkEnvelopeCodec.DefaultContentType,
            correlationId,
            null,
            null,
            null,
            null);
        return ZLinkEnvelopeCodec.EncodeParts(replyHeader, reply, replyType, codecs);
    }

    // forceFrameworkOrigin marks the reply as framework-generated even when the
    // caught exception carries no origin (internal infrastructure packets whose
    // failures never come from an application handler).
    public static IReadOnlyList<Message> EncodeErrorParts(
        string channelName,
        string messageName,
        string? correlationId,
        Exception exception,
        bool forceFrameworkOrigin = false)
    {
        var errorCode = exception is ZLinkFrameworkException frameworkException
            ? ZLinkErrorWireNames.Name(frameworkException.Kind)
            : exception.GetType().Name;
        var replyHeader = new ZLinkEnvelopeHeader(
            ZLinkMessageKind.Error,
            channelName,
            messageName,
            ZLinkEnvelopeCodec.DefaultContentType,
            correlationId,
            null,
            null,
            errorCode,
            exception.Message)
        {
            // zlink.origin=framework marker for framework-generated errors only
            // (stale-route contract); application handler errors stay unmarked.
            Metadata = ZLinkErrorOriginWire.ErrorReplyMetadata(
                exception, forceFrameworkOrigin)
        };
        return ZLinkEnvelopeCodec.EncodeParts(replyHeader, null, null, null);
    }

    public static IReadOnlyList<Message> EncodeProtocolErrorParts(
        string channelName,
        ZLinkEnvelopeHeader request,
        string message)
    {
        // Spec 27 §4/§7: correlation only; flow fields come from the ambient
        // flow context at encode time, so an Off host adds none.
        var replyHeader = new ZLinkEnvelopeHeader(
            ZLinkMessageKind.Error,
            channelName,
            ZLinkEnvelopeCodec.ProtocolErrorMessageName(request),
            ZLinkEnvelopeCodec.DefaultContentType,
            request.CorrelationId,
            null,
            null,
            ZLinkErrorWireNames.Name(ZLinkFrameworkErrorKind.ProtocolError),
            message)
        {
            // Protocol errors are framework-generated by definition.
            Metadata = ZLinkErrorOriginWire.FrameworkOriginMetadata()
        };
        return ZLinkEnvelopeCodec.EncodeParts(replyHeader, null, null, null);
    }
}
