<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <TargetFrameworks>$(ZLinkFrameworkTargetFrameworks)</TargetFrameworks>
        <AssemblyName>Zlink.Framework.Codecs.MessagePack</AssemblyName>
        <RootNamespace>Zlink.Framework.Codecs.MessagePack</RootNamespace>
        <Description>MessagePack codec extension for the ZLink .NET framework.</Description>
        <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MessagePack"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Zlink.Framework/Zlink.Framework.csproj"/>
    </ItemGroup>
</Project>
