plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.1.0'
}

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(22)
}

dependencies {
    implementation project(':')
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5:2.1.0'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.9.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

test {
    useJUnitPlatform()
}
