plugins {
    alias(libs.plugins.kotlin.jvm)
}

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(libs.versions.java.get().toInteger())
}

dependencies {
    implementation project(':')
    testImplementation libs.kotlin.test.junit5
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.9.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

test {
    useJUnitPlatform()
    jvmArgs '--enable-native-access=ALL-UNNAMED', '--illegal-native-access=deny'
}
