#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Generate binding errno resources with the target platform's C compiler."""

import argparse
import hashlib
import pathlib
import shutil
import subprocess
import sys
import tempfile

NAMES = """ENOENT ESRCH EINTR EBADF EAGAIN EDEADLK ENOMEM EFAULT EACCES EBUSY
EEXIST EINVAL EPROTO EADDRINUSE ENOTSUP ENOTCONN ECONNREFUSED EHOSTUNREACH
ESHUTDOWN ETIMEDOUT EIO ENOBUFS ESTALE ECANCELED ENOTSOCK EMSGSIZE
EPROTONOSUPPORT EOPNOTSUPP EAFNOSUPPORT EADDRNOTAVAIL ENETDOWN ENETUNREACH ENETRESET
ECONNABORTED ECONNRESET EINPROGRESS EALREADY EPROTOTYPE EOVERFLOW EFSM
ENOCOMPATPROTO ETERM EMTHREAD""".split()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("platform", choices=("linux", "darwin", "windows"))
    parser.add_argument("--include", required=True, type=pathlib.Path,
                        help="Installed Core public header directory")
    parser.add_argument("--compiler", default="cc")
    parser.add_argument("--errno-header", type=pathlib.Path,
                        help="Target OS public errno.h for header-only cross generation")
    parser.add_argument("--cflag", action="append", default=[])
    parser.add_argument("--output", type=pathlib.Path,
                        default=pathlib.Path(__file__).parent)
    args = parser.parse_args()
    host = "windows" if sys.platform == "win32" else sys.platform
    if args.platform != host and not args.errno_header:
        parser.error("Cross generation requires the target OS public errno header")
    with tempfile.TemporaryDirectory(prefix="zlink-1154-errno-") as temporary:
        directory = pathlib.Path(temporary)
        source = directory / "errno.c"
        executable = directory / ("errno.exe" if args.platform == "windows" else "errno")
        if args.errno_header:
            shutil.copyfile(args.errno_header, directory / "errno.h")
        source.write_text('#include <stdio.h>\n#include <zlink_errno.h>\n'
                          'int main(void) {\n' + ''.join(
                              f'printf("{name}=%d\\n", {name});\n' for name in NAMES)
                          + 'return 0;\n}\n', encoding="utf-8")
        if pathlib.Path(args.compiler).name.lower() in ("cl", "cl.exe"):
            command = [args.compiler, "/nologo", str(source),
                       f"/I{args.include.resolve()}", f"/Fe:{executable}",
                       f"/Fo:{directory / 'errno.obj'}"]
        else:
            command = [args.compiler, str(source), "-I", str(directory),
                       "-I", str(args.include.resolve()), *args.cflag,
                       "-o", str(executable)]
        subprocess.run(command, check=True, cwd=directory)
        values = subprocess.check_output([str(executable)], text=True)
    args.output.mkdir(parents=True, exist_ok=True)
    destination = args.output / f"{args.platform}.properties"
    destination.write_text(
        "# Generated by generate.py from the platform errno.h and zlink_errno.h.\n"
        "# Regenerate on the target platform; do not edit individual values.\n"
        + "# Core header SHA-256: "
        + hashlib.sha256((args.include / "zlink_errno.h").read_bytes()).hexdigest()
        + "\n"
        + ("# Target errno header SHA-256: "
           + hashlib.sha256(args.errno_header.read_bytes()).hexdigest() + "\n"
           if args.errno_header else "")
        + values.replace("\r\n", "\n"), encoding="utf-8")


if __name__ == "__main__":
    main()
