<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>$(ZLinkFrameworkTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Zlink.Framework.UnitTests/Zlink.Framework.UnitTests.csproj"/>
    </ItemGroup>
</Project>
