// SPDX-License-Identifier: MPL-2.0

export const ContextOption = Object.freeze({
  IO_THREADS: 1,
  MAX_SOCKETS: 2,
  SOCKET_LIMIT: 3,
  THREAD_PRIORITY: 3,
  THREAD_SCHED_POLICY: 4,
  MAX_MSGSZ: 5,
  MSG_T_SIZE: 6,
  THREAD_AFFINITY_CPU_ADD: 7,
  THREAD_AFFINITY_CPU_REMOVE: 8,
  THREAD_NAME_PREFIX: 9,
  BLOCKY: 10,
  AUTO_HWM_ENABLE: 12,
  AUTO_HWM_RECALC_DEBOUNCE_MS: 14,
  AUTO_HWM_PROFILE: 17,
  AUTO_HWM_MEMORY_LIMIT_BYTES: 19,
  AUTO_HWM_RUNTIME_MEMORY_LIMIT_BYTES: 20,
  AUTO_HWM_CORE_BUDGET_BYTES: 21
} as const);
