#pragma once
#include "handlers.hpp"
#include "../Shared/http.hpp"
#include "../Shared/public_metrics.hpp"
#include <zlink/locations/redis.hpp>

namespace perf {
class application_t final:public fw::hosted_service_t {
    fw::app_t &app;measurement_t &m;public_metrics_t &metrics;fw::service_provider_t *services=nullptr;fw::framework_runtime_t *host=nullptr;fw::route_client_t *route=nullptr;fw::channel_client_t *channel=nullptr;fw::actor_client_t *actor=nullptr;fw::actor_manager_t *actors=nullptr;fw::spot_manager_t *spots=nullptr;fw::publisher_t *publisher=nullptr;
    fw::route_mesh_runtime_t *mesh_runtime=nullptr;fw::client_server_runtime_t *client_server=nullptr;fw::fanout_runtime_t *fanout_runtime=nullptr;
    std::unique_ptr<http_listener_t> admin,trigger_listener;std::thread coordinator;std::atomic_bool stopping=false;std::atomic_bool objects_ready=false,prepared=false,preparing=false;
    template<typename T>T *optional(){auto value=services->get<T>();return value?&value->get():nullptr;}
    struct slot_t {int stream;std::shared_ptr<operation_t> op;std::optional<fw::task_t<void>> task;};
    std::vector<slot_t> slots;std::vector<std::uint64_t> sequences;std::uint64_t publisher_sequence=0;std::vector<fw::task_t<void>> retained;
  public:
    application_t(fw::app_t &value,measurement_t &measurement,public_metrics_t &provider):app(value),m(measurement),metrics(provider){}
    json public_status(){const auto status=host->status();const auto &capacity=status.capacity;const auto &queue=capacity.application_job_queue;const auto &core=capacity.core_hwm;json value={{"host",{{"state",static_cast<int>(status.state)},{"isReady",status.is_ready},{"acceptingWork",status.accepting_work},{"sequence",std::to_string(status.sequence)},{"capacity",{{"measurementEpoch",std::to_string(capacity.measurement_epoch)},{"applicationJobQueue",{{"configuredManualMax",queue.configured_manual_max?json(*queue.configured_manual_max):json(nullptr)},{"effectiveProcessorCount",queue.effective_processor_count},{"effectiveMaxQueuedApplicationJobs",queue.effective_max_queued_application_jobs},{"queuedApplicationJobs",queue.queued_application_jobs},{"permitsInUse",queue.permits_in_use},{"peakPermitsInUse",queue.peak_permits_in_use},{"capacityWaiters",queue.capacity_waiters},{"capacityWaitCount",std::to_string(queue.capacity_wait_count)},{"capacityWaitDurationNs",std::to_string(queue.capacity_wait_duration.count())},{"pressureState",static_cast<int>(queue.pressure_state)}}},{"coreHwm",{{"effectiveBudgetBytes",std::to_string(core.effective_budget_bytes)},{"currentAccountedBytes",std::to_string(core.current_accounted_bytes)},{"peakAccountedBytes",std::to_string(core.peak_accounted_bytes)},{"completionPendingMessageCount",std::to_string(core.completion_pending_message_count)}}}}}}}};
        if(mesh_runtime&&!m.config.text("meshName").empty()){const auto mesh=mesh_runtime->snapshot(m.config.text("meshName"));json channels=json::array();for(const auto &entry:mesh.channels)channels.push_back({{"channelName",entry.channel_name},{"isReady",entry.is_ready},{"readyTargetCount",entry.ready_target_count}});value["routeMesh"]={{"meshName",mesh.mesh_name},{"isReady",mesh.is_ready},{"readyPeerCount",mesh.ready_peer_count},{"channels",channels},{"sequence",std::to_string(mesh.sequence)}};}if(client_server&&!m.config.text("channelName").empty()){const auto cs=client_server->snapshot(m.config.text("channelName"));value["clientServer"]={{"selectable",cs.selectable},{"readyServerCount",cs.ready_server_count},{"pendingRequestCount",cs.pending_request_count}};}if(fanout_runtime&&m.config.publish()){const auto ps=fanout_runtime->snapshot(m.config.text("channelName"));value["fanout"]={{"readyConnectionCount",ps.ready_connection_count},{"connectionIntentCount",ps.connection_intent_count},{"sequence",std::to_string(ps.sequence)}};}return value;
    }
    bool infrastructure_ready(const json &status){if(!status.at("host").at("isReady").get<bool>())return false;if(m.config.publish())return m.config.source()||status.at("fanout").at("readyConnectionCount").get<int>()>0;if(m.config.cs()){if(m.config.actor()&&m.config.text("role")=="session"&&m.config.value.value("objectRole","")=="Client")return status.at("routeMesh").at("isReady").get<bool>()&&status.at("routeMesh").at("readyPeerCount").get<int>()>0;return true;}if(m.config.value.value("topology",json(nullptr))=="clientserver")return !m.config.source()||status.at("clientServer").at("selectable").get<bool>();if(status.contains("routeMesh")&&!status.at("routeMesh").at("isReady").get<bool>())return false;if(m.config.source()&&m.config.value.value("objectRole","")=="Client"&&(m.config.actor()||m.config.spot())&&!m.config.driven())return status.at("routeMesh").at("readyPeerCount").get<int>()>0;if(m.config.source()&&!m.config.actor()&&(!m.config.spot()||m.config.driven())){for(const auto &entry:status.at("routeMesh").at("channels"))if(entry.at("channelName")==m.config.value.at("channelName"))return entry.at("isReady").get<bool>()&&entry.at("readyTargetCount").get<int>()>0;return false;}return true;}
    bool infrastructure_ready(){return infrastructure_ready(public_status());}
    json ready(){const auto status=public_status();const bool infra=infrastructure_ready(status);std::lock_guard lock(m.mutex);const bool consumer=m.config.cs()||!m.setup.empty();const bool errors=!m.setup_failed;json reasons=json::array();if(!infra)reasons.push_back("Public host/topology is not ready.");if(!objects_ready)reasons.push_back("Public object preparation incomplete.");if(!consumer)reasons.push_back("Typed probe/consumer marker evidence missing.");if(!errors)reasons.push_back("Application failure recorded.");json evidence=m.setup;evidence.push_back({{"kind","publicStatus"},{"source","public Framework runtime snapshots"},{"observedValue",status}});return {{"runId",m.config.value.at("runId")},{"cellId",m.config.value.at("cellId")},{"role",m.config.value.at("role")},{"roleInstance",m.config.value.at("roleInstance")},{"infrastructureReady",infra},{"objectsReady",objects_ready.load()},{"consumersReady",consumer},{"ready",infra&&objects_ready&&consumer&&errors},{"observedAtUnixMs",unix_ms()},{"evidence",evidence},{"reasons",reasons}};}
    fw::task_t<void> prepare_objects(){if(m.config.value.value("objectRole","")!="Server"){objects_ready=true;co_return;}if(m.config.spot())for(const std::string id:m.config.value.at("spotIds"))co_await spots->get_or_create(fw::spot_id_t(id),"perf-spot").in_mesh(m.config.text("meshName")).timeout(std::chrono::milliseconds(m.config.workload().at("setupTimeoutMs").get<int>())).async();if(m.config.actor())for(const std::string id:m.config.value.at("actorIds"))created_actor(co_await actors->get_or_create(fw::actor_id_t(id),"perf-actor").in_mesh(m.config.text("meshName")).timeout(std::chrono::milliseconds(m.config.workload().at("setupTimeoutMs").get<int>())).async());objects_ready=true;}
    fw::task_t<void> probe(){const auto request=m.request(0,0,true);const auto timeout=std::chrono::milliseconds(m.config.workload().at("setupTimeoutMs").get<int>());if(m.config.publish()){auto fields=request.fields;for(const auto *key:{"clientId","correlationId","returnSpotId","returnChannel"})fields.erase(key);fields["topic"]="perf.echo";co_await publisher->publish(m.config.text("channelName"),"perf.echo",event_t{fields}).async();}
        else{reply_t reply;if(m.config.actor())reply=co_await actor->request(fw::actor_id_t(m.config.target("actorIds",0)),probe_t{request.fields}).timeout(timeout).async<reply_t>();else if(m.config.spot())reply=co_await route->request_to_spot(fw::spot_id_t(m.config.target("spotIds",0)),probe_t{request.fields}).timeout(timeout).async<reply_t>();else reply=co_await (m.config.value.value("topology",json(nullptr))=="clientserver"?channel->request_to_channel(m.config.text("channelName"),probe_t{request.fields}):route->request_to_channel(m.config.text("channelName"),probe_t{request.fields})).timeout(timeout).async<reply_t>();m.validate_reply(request,reply);if(m.config.driven()){auto remote=co_await route->request_to_channel(m.config.text("channelName"),probe_t{request.fields}).timeout(timeout).async<reply_t>();m.validate_reply(request,remote);}}
        std::lock_guard lock(m.mutex);m.setup.push_back({{"kind",m.config.publish()?"publishProbeAdmission":"typedProbeEcho"},{"source","public typed call and full payload validation"},{"observedValue",true}});prepared=true;}
    json prepare(){std::unique_lock lock(m.mutex);if(prepared){lock.unlock();return {{"ok",true},{"ready",ready()}};}if(preparing)throw std::runtime_error("Concurrent prepare is unsupported.");preparing=true;lock.unlock();try{prepare_objects().result().value();if(m.config.source()&&!m.config.cs())probe().result().value();lock.lock();prepared=true;preparing=false;lock.unlock();return {{"ok",true},{"ready",ready()}};}catch(const std::exception &failure){lock.lock();preparing=false;m.error(failure,false,true);throw;}}
    fw::task_t<void> run_one(std::shared_ptr<operation_t> op){auto request=op->request;const int stream=request.fields.at("clientId");const auto timeout=std::chrono::milliseconds(m.config.timeout());
        try{if(m.config.driven()){
                const auto spot=fw::spot_id_t(m.config.target("spotIds",stream));drive_t driver;driver.fields["echo"]=request.fields;auto call=route->request_to_spot(spot,driver);call.timeout(timeout);const auto result=co_await call.async<drive_reply_t>();m.record("driverLatencyMs",ticks()-op->started);
                if(!result.fields.at("started").get<bool>()){std::lock_guard lock(m.mutex);if(!op->done){op->done=true;--m.inflight;m.operations.erase(request.fields.at("correlationId"));}co_return;}
                if(!m.config.send()&&!m.config.correlated())m.validate_reply(request,reply_t{result.fields.at("echo")});co_return;
            }
            const bool send=m.config.send()||m.config.correlated();if(m.config.correlated()){request.fields["returnChannel"]=m.config.value.at("channelName");std::lock_guard lock(m.mutex);op->request=request;m.correlate(op);}
            m.direction(m.config.publish()?"event":send?"send":"request",m.config.request_bytes());
            if(m.config.publish()){
                auto fields=request.fields;for(const auto *key:{"clientId","correlationId","returnSpotId","returnChannel"})fields.erase(key);fields["topic"]="perf.echo";const event_t event{fields};auto call=publisher->publish(m.config.text("channelName"),"perf.echo",event);co_await call.async();m.admission(request,op->started);m.finish(op);
            }else if(send){
                if(m.config.actor()){const auto id=fw::actor_id_t(m.config.target("actorIds",stream));auto call=actor->send(id,request);co_await call.async();}
                else{const auto id=fw::spot_id_t(m.config.target("spotIds",stream));auto call=route->send_to_spot(id,request);co_await call.async();}
                m.admission(request,op->started);if(!m.config.correlated())m.finish(op);
            }else{
                reply_t reply;if(m.config.actor()){const auto id=fw::actor_id_t(m.config.target("actorIds",stream));auto call=actor->request(id,request);call.timeout(timeout);reply=co_await call.async<reply_t>();}
                else if(m.config.spot()){const auto id=fw::spot_id_t(m.config.target("spotIds",stream));auto call=route->request_to_spot(id,request);call.timeout(timeout);reply=co_await call.async<reply_t>();}
                else{auto call=m.config.value.value("topology",json(nullptr))=="clientserver"?channel->request_to_channel(m.config.text("channelName"),request):route->request_to_channel(m.config.text("channelName"),request);call.timeout(timeout);reply=co_await call.async<reply_t>();}
                m.validate_reply(request,reply);m.finish(op);
            }
        }catch(const std::exception &failure){std::lock_guard lock(m.mutex);
            if(m.config.driven()){m.bump("driver.failed");m.error(failure);if(!op->primary&&!op->done){op->done=true;--m.inflight;m.operations.erase(request.fields.at("correlationId"));}m.changed.notify_all();}
            else{m.pending.erase(request.fields.at("correlationId"));m.terminal[request.fields.at("correlationId")]=false;m.finish(op,&failure);}
        }
    }
    void coordinate(){std::int64_t next_sample=0;try{while(!stopping){std::unique_lock lock(m.mutex);if(!m.running){m.changed.wait_for(lock,std::chrono::milliseconds(100));continue;}const bool source=m.config.source()&&!m.config.cs();if(source&&slots.empty()){const auto streams=m.config.workload().at("logicalStreams").get<int>();sequences.assign(streams,0);for(int stream=0;stream<streams;++stream)for(int i=0;i<m.config.workload().at("inflight").get<int>();++i)slots.push_back({stream,{},{}});}lock.unlock();if(source){for(auto &slot:slots){if(slot.task&&slot.task->await_ready()){slot.task->result().value();slot.task.reset();}if(!slot.task&&(!slot.op||slot.op->done)&&m.can_issue()){const auto sequence=m.config.publish()?++publisher_sequence:++sequences[slot.stream];slot.op=m.begin(m.request(m.config.publish()?0:slot.stream,sequence));if(slot.op)slot.task.emplace(run_one(slot.op));}}m.expire();}const auto sample_at=ticks();if(sample_at>=next_sample){const auto status=public_status();const auto values=metrics.reader->collect();lock.lock();m.sample();m.public_metrics=values;m.public_samples.push_back({{"observedTicks",std::to_string(sample_at)},{"status",status}});lock.unlock();next_sample=sample_at+100000000;}lock.lock();const auto at=ticks();if(at>=m.end){m.end_window();const bool drained=m.inflight==0&&m.active==0;const bool settle_end=at>=m.end+m.config.workload().at("settleTimeoutMs").get<std::int64_t>()*1000000;if((source&&drained)||settle_end){m.complete();for(auto &slot:slots)if(slot.task)retained.push_back(std::move(*slot.task));slots.clear();}}m.changed.wait_for(lock,std::chrono::milliseconds(1));}}catch(const std::exception &failure){m.error(failure,false,true);m.complete();}}
    fw::task_t<void> start(fw::service_provider_t &provider) override{services=&provider;host=&provider.get_required<fw::framework_runtime_t>();route=optional<fw::route_client_t>();channel=optional<fw::channel_client_t>();actor=optional<fw::actor_client_t>();actors=optional<fw::actor_manager_t>();spots=optional<fw::spot_manager_t>();publisher=optional<fw::publisher_t>();mesh_runtime=optional<fw::route_mesh_runtime_t>();client_server=optional<fw::client_server_runtime_t>();fanout_runtime=optional<fw::fanout_runtime_t>();objects_ready=m.config.value.value("objectRole","")!="Server"||(!m.config.actor()&&!m.config.spot());
        admin=std::make_unique<http_listener_t>(m.config.text("metricsUrl"),[this](const std::string &method,const std::string &path,const json &body)->std::pair<int,json>{if(method=="GET"&&path=="/perf/ready")return {200,ready()};if(method=="GET"&&(path=="/perf/metrics"||path=="/perf/stats"))return {200,m.snapshot(public_status())};if(method=="POST"&&path=="/perf/reset"){auto result=m.reset(body,host);return {result.at("ok").get<bool>()?200:409,result};}if(method=="POST"&&path=="/perf/stop"){app.request_stop();return {200,{{"ok",true}}};}return {404,{{"reason","Unknown admin route."}}};});
        trigger_listener=std::make_unique<http_listener_t>(m.config.text("applicationTriggerUrl"),[this](const std::string &method,const std::string &path,const json &body)->std::pair<int,json>{if(method=="POST"&&path=="/app/perf/prepare")return {200,prepare()};if(method=="POST"&&path=="/app/perf/start"){if(!ready().at("ready").get<bool>())return {409,{{"reason","Preparation evidence incomplete."}}};auto result=m.trigger(body);return {result.at("accepted").get<bool>()?200:409,result};}return {404,{{"reason","Unknown application route."}}};});coordinator=std::thread([this]{coordinate();});co_return;}
    void request_stop() noexcept override{stopping=true;m.changed.notify_all();}void stop() noexcept override{request_stop();if(coordinator.joinable())coordinator.join();trigger_listener.reset();admin.reset();}
};

inline int run_server(config_t config,int argc,char **argv){if(config.workload().at("requestPayloadBytes")!=64||config.workload().at("responsePayloadBytes")!=4096||config.workload().at("sendPayloadBytes")!=4096)throw std::invalid_argument("Default logical bytes must be 64/4096/4096.");if(uri_t(config.text("metricsUrl")).port==uri_t(config.text("applicationTriggerUrl")).port)throw std::invalid_argument("Control listener ports must differ.");public_metrics_t metrics;auto app=fw::app_t::create();if(config.diagnostics_enabled()){const auto diagnostics=config.value.value("diagnostics",json(nullptr));if(diagnostics.is_object())app.logging().use_file(diagnostics.at("flowFile"));}auto state=std::make_unique<measurement_t>(config,config.source());auto &m=*state;auto &options=app.add_zlink_framework();options.services().add_singleton<measurement_t>(std::move(state));options.set_default_request_timeout(std::chrono::milliseconds(config.timeout()));options.worker().max_threads(config.workload().at("workerPoolSize").get<int>()).min_threads(config.workload().at("workerPoolSize").get<int>()).idle_timeout(std::chrono::milliseconds(60000));options.configure_network().set_bind_host("127.0.0.1").set_advertise_host("127.0.0.1");app.set_message_flow_mode(config.diagnostics_enabled()?fw::message_flow_log_mode_t::normal:fw::message_flow_log_mode_t::off);
    if(config.value.contains("store")&&!config.value.at("store").is_null()){const auto &store=config.value.at("store");if(store.at("provider")!="redis")throw std::invalid_argument("Only public Redis provider is supported.");options.add_location_store<fw::redis::redis_location_store_t>().set_connection_string(store.at("endpoint")).set_key_prefix(store.at("namespace").get<std::string>()+":location");}
    const auto mesh_endpoint=config.text(config.cs()?"meshEndpoint":"listenerEndpoint");if(!config.publish()&&!mesh_endpoint.empty()&&config.value.value("topology",json(nullptr))!="clientserver"){auto mesh=options.add_route_mesh(config.text("meshName")).listen(mesh_endpoint).set_placement_weight(config.value.value("objectRole","")=="Client"?0:100);if(!config.value.contains("store")||config.value.at("store").is_null())mesh.set_routing_id(zlink::routing_id_t::from("perf-"+config.text("role")+"-"+std::to_string(config.value.value("roleInstance",0))));std::set<std::string> peers;for(const std::string peer:config.value.value("peerEndpoints",json::array()))peers.insert(peer);if(!config.text("peerEndpoint").empty())peers.insert(config.text("peerEndpoint"));for(const auto &peer:peers)if(peer!=mesh_endpoint)mesh.peer_connections().connect(peer);mesh.configure_router_socket().send_timeout=std::chrono::milliseconds(config.workload().at("socketSendTimeoutMs").get<int>());
        if(config.value.value("objectRole","")=="Server"){auto objects=mesh.objects().server();if(config.spot())objects.add_spot_factory<spot_t,measurement_t,fw::route_client_t>("perf-spot").set_execution_mode(fw::user_spot_execution_mode_t::spot_wide).disable_relocation();if(config.actor()){objects.add_entry_spot<entry_t,measurement_t,fw::route_client_t>();objects.add_actor_factory<actor_t,actor_factory_t>("perf-actor").disable_relocation();}}else if(config.value.value("objectRole","")=="Client")mesh.objects().client();else if(config.value.value("objectRole","")=="None")mesh.set_object_role(fw::object_role_t::none);
        if(!config.text("channelName").empty()){if(!config.source()||config.correlated()){auto channel=mesh.channel(config.text("channelName")).server();channel.add_request_handler<channel_request_handler_t,request_t,reply_t>().add_request_handler<channel_probe_handler_t,probe_t,reply_t>();if(config.send()||config.correlated())channel.add_send_handler<channel_send_handler_t,request_t>();if(config.source()&&config.correlated())channel.add_send_handler<channel_return_handler_t,reply_t>();}else mesh.channel(config.text("channelName")).client();}}
    if(!config.cs()&&!config.publish()&&config.value.value("topology",json(nullptr))=="clientserver"){auto cs=options.add_client_server_channel(config.text("channelName"));if(config.source())cs.client().connect(config.text("peerEndpoint"));else cs.server().listen(static_cast<unsigned short>(std::stoul(uri_t(config.text("listenerEndpoint")).port))).set_bind_host("127.0.0.1").add_request_handler<channel_request_handler_t,request_t,reply_t>().add_request_handler<channel_probe_handler_t,probe_t,reply_t>();}
    if(config.cs()&&(config.text("listenerEndpoint").starts_with("ws://")||config.text("listenerEndpoint").starts_with("wss://"))){auto stream=options.add_stream_node("perf-session").bind(config.text("listenerEndpoint"));if(config.actor()){options.services().add_scoped<session_t,measurement_t,fw::actor_manager_t>();stream.enable_actor_dispatch();stream.register_session<session_t>();}else{options.services().add_scoped<baseline_session_t,measurement_t>();stream.register_session<baseline_session_t>();}}
    if(config.publish()){auto ps=options.add_fanout_channel(config.text("channelName"));if(config.source())ps.enable_publisher(config.text("fanoutEndpoint",config.text("listenerEndpoint"))).set_automatic_routing_id_prefix(config.text("channelName"));else{ps.enable_subscriber();options.services().add_transient<fanout_handler_t,measurement_t>();options.handlers().group("perf-publish").add_publish<fanout_handler_t>();ps.add_handler_group("perf-publish");}}
    app.add_hosted_service(std::make_unique<application_t>(app,m,metrics));return app.run(argc,argv);
}
}
