#pragma once
#include "histogram.hpp"
#include <zlink/framework.hpp>
#include <atomic>
#include <condition_variable>
#include <mutex>
#include <set>
#include <thread>
#include <tuple>
#include <sys/resource.h>
#include <sched.h>
#include <unistd.h>

namespace perf {
namespace fw=zlink::framework;
struct operation_t { request_t request;std::int64_t started=0,primary_started=0;std::atomic_bool done=false;bool public_done=false,primary=false; };
struct measurement_t {
    config_t config;bool primary;std::recursive_mutex mutex;std::condition_variable_any changed;
    std::string domain,phase="setup",reset_seq="0";std::int64_t start=0,end=0,settled=0;
    json start_unix=nullptr,end_unix=nullptr,reset_ack=nullptr,setup=json::array(),errors=json::array(),public_samples=json::array(),public_metrics=json::array(),worker_observation=nullptr;
    bool running=false,sealed=false,setup_failed=false;std::uint64_t active=0,inflight=0,max_inflight=0,connected=0,connection_failures=0,requested_connections=0;
    double cpu_started=0,cpu_used=0;std::int64_t sample_ticks=0;std::uint64_t sample_cpu_ns=0,cpu_start_ns=0;json cpu_samples=json::array();std::map<std::size_t,std::pair<std::uint64_t,std::uint64_t>> cpu_bins;std::uint64_t rss_peak=0,slo_met=0,slo_window_met=0;
    std::map<std::string,std::uint64_t> counts,by_kind,harness,language;
    std::map<std::string,histogram_t> hist;
    std::map<std::size_t,std::map<std::string,std::uint64_t>> bins;
    ranges_t attempted,window_admission,settle_admission,window_delivery,settle_delivery,all_delivery;
    std::map<std::string,std::shared_ptr<operation_t>> operations,pending;
    std::map<std::string,bool> terminal;std::map<std::string,json> starts;
    std::map<int,std::string> patterns;
    explicit measurement_t(config_t cfg,bool owner):config(std::move(cfg)),primary(owner),domain("process-"+std::to_string(getpid())+"-"+std::to_string(ticks())) {(void)histogram_t::load_bounds();patterns.emplace(64,pattern(64));patterns.emplace(4096,pattern(4096));}
    void bump(const std::string &key,std::uint64_t n=1,std::int64_t at=ticks()){std::lock_guard lock(mutex);counts[key]+=n;if(start&&at>=start&&at<end&&!sealed){auto &bin=bins[static_cast<std::size_t>((at-start)/100000000)];bin[key]+=n;if(key=="messages.sent"&&!config.send()&&!config.publish())bin["slo.eligible"]+=n;}}
    json time_series(){json result=json::array();if(!start)return result;const auto ns=end-start;
        for(std::int64_t offset=0;offset<ns;offset+=100000000){const auto index=static_cast<std::size_t>(offset/100000000);json values=json::object();auto found=bins.find(index);if(found!=bins.end())for(auto[key,n]:found->second)values[key]=std::to_string(n);
            json percent=nullptr,reasons=json::object();const auto observation=cpu_bins.find(index);if(observation!=cpu_bins.end()&&observation->second.first)percent=100.0*observation->second.second/observation->second.first;else reasons["/cpuPercent"]=reason("NO_SAMPLES","No actual CPU sample span starts in this bin.");
            result.push_back({{"offsetMs",offset/1e6},{"durationMs",std::min<std::int64_t>(100000000,ns-offset)/1e6},{"counts",values},{"cpuPercent",percent},{"nullReasons",reasons}});
        }return result;
    }
    static std::uint64_t cpu_ns(){rusage usage{};if(getrusage(RUSAGE_SELF,&usage)!=0)throw std::runtime_error("Cannot observe public process CPU usage.");return (static_cast<std::uint64_t>(usage.ru_utime.tv_sec)+usage.ru_stime.tv_sec)*1000000000ULL+(static_cast<std::uint64_t>(usage.ru_utime.tv_usec)+usage.ru_stime.tv_usec)*1000ULL;}
    static double cpu(){return cpu_ns()/1e9;}
    static unsigned affinity_processors(){cpu_set_t cpus;CPU_ZERO(&cpus);if(sched_getaffinity(0,sizeof(cpus),&cpus)!=0)throw std::runtime_error("Cannot observe public process CPU affinity.");return static_cast<unsigned>(CPU_COUNT(&cpus));}
    void sample(bool force=false){std::lock_guard lock(mutex);if(!start||sealed||(phase=="settle"&&!force))return;const auto at=ticks();if(!force&&sample_ticks&&at-sample_ticks<100000000)return;const auto cumulative=cpu_ns();
        std::ifstream stream("/proc/self/statm");std::uint64_t total=0,resident=0;if(!(stream>>total>>resident))throw std::runtime_error("Cannot observe current process RSS.");rss_peak=std::max(rss_peak,resident*static_cast<std::uint64_t>(sysconf(_SC_PAGESIZE)));
        if(sample_ticks){if(at<=sample_ticks||cumulative<sample_cpu_ns)throw std::range_error("Invalid actual CPU sample span or negative CPU delta.");if(sample_ticks>=start&&sample_ticks<end){const auto offset=sample_ticks-start;const auto bin=static_cast<std::size_t>(offset/100000000);const auto duration=static_cast<std::uint64_t>(at-sample_ticks),delta=cumulative-sample_cpu_ns;auto &totals=cpu_bins[bin];totals.first+=duration;totals.second+=delta;cpu_samples.push_back({{"binIndex",bin},{"startOffsetMs",offset/1e6},{"endOffsetMs",(at-start)/1e6},{"observedDurationNs",std::to_string(duration)},{"cpuDeltaNs",std::to_string(delta)}});}}
        sample_ticks=at;sample_cpu_ns=cumulative;
    }
    bool can_issue() {std::lock_guard lock(mutex);return running&&!sealed&&ticks()<end;}
    request_t request(int stream,std::uint64_t sequence,bool probe=false) {std::lock_guard lock(mutex);const std::string p=probe||reset_seq=="0"?"warmup":"measured";return {{{"runId",config.value.at("runId")},{"cellId",config.value.at("cellId")},{"resetSeq",probe?"0":reset_seq},{"phase",p},{"clientId",stream},{"sequence",std::to_string(sequence)},{"correlationId",config.text("cellId")+"/"+p+"/"+std::to_string(stream)+"/"+std::to_string(sequence)},{"scheduledTicks",nullptr},{"sentTicks",std::to_string(ticks())},{"clockDomainId",domain},{"returnSpotId",nullptr},{"returnChannel",nullptr},{"payload",patterns.at(config.request_bytes())}}};}
    void validate(const request_t &request) {std::lock_guard lock(mutex);const auto &v=request.fields;const auto seq=decimal(v.at("sequence"));(void)seq;decimal(v.at("resetSeq"));
        if(v.at("runId")!=config.value.at("runId")||v.at("cellId")!=config.value.at("cellId")||!v.at("clientId").is_number_integer()||v.at("clientId").get<int>()<0||v.at("clockDomainId").get<std::string>().empty())throw validation_error("IdentityMismatch","Request identity differs.");
        const std::string p=v.at("phase");if((p!="warmup"&&p!="measured")||v.at("correlationId")!=config.text("cellId")+"/"+p+"/"+std::to_string(v.at("clientId").get<int>())+"/"+v.at("sequence").get<std::string>())throw validation_error("IdentityMismatch","Application correlation differs.");
        if((p=="measured"&&v.at("resetSeq")!=reset_seq)||(p=="warmup"&&v.at("resetSeq")!="0"))throw validation_error("PhaseMismatch","Phase/reset sequence differs.");
        if(!v.at("scheduledTicks").is_null())signed_decimal(v.at("scheduledTicks"));signed_decimal(v.at("sentTicks"));validate_payload(v,patterns.at(config.request_bytes()));if(p=="warmup"&&reset_seq!="0")bump("load.lateWarmupMessages");
    }
    void observe(const request_t &request) {try{validate(request);}catch(const std::exception &failure){error(failure);throw;}std::lock_guard lock(mutex);if(setup.empty())setup.push_back({{"kind","typedProbe"},{"source","public typed application handler"},{"observedValue",{{"clientId",request.fields.at("clientId")},{"sequence",request.fields.at("sequence")}}}});}
    reply_t reply(const request_t &request) {auto v=request.fields;v.erase("sentTicks");v.erase("scheduledTicks");v.erase("returnSpotId");v.erase("returnChannel");v["receivedTicks"]=std::to_string(ticks());v["clockDomainId"]=domain;v["payload"]=patterns.at(config.workload().at("responsePayloadBytes").get<int>());return {std::move(v)};}
    void validate_reply(const request_t &request,const reply_t &reply) {validate_identity(request.fields,reply.fields);validate_payload(reply.fields,patterns.at(config.workload().at("responsePayloadBytes").get<int>()));}
    void direction(const std::string &kind,int bytes) {std::lock_guard lock(mutex);if(start&&ticks()<end&&!sealed){bump("applicationMessages."+kind);bump("applicationPayloadBytes."+kind,bytes);}}
    void record(const std::string &key,std::int64_t ns,std::int64_t at=ticks()) {std::lock_guard lock(mutex);if(key!="latencyMs"&&key!="settleLatencyMs"&&(!start||at>=end||sealed))return;hist.try_emplace(key).first->second.record(ns);}
    std::shared_ptr<operation_t> begin(request_t request) {std::lock_guard lock(mutex);const auto at=ticks();if(!running||sealed||at>=end)return {};auto op=std::make_shared<operation_t>();op->request=std::move(request);op->started=at;op->primary_started=at;op->primary=!config.driven();bump(config.driven()?"driver.issued":"messages.sent",1,at);operations.emplace(op->request.fields.at("correlationId"),op);if(!config.driven())attempted.add(op->request.fields.at("clientId"),decimal(op->request.fields.at("sequence")));max_inflight=std::max(max_inflight,++inflight);return op;}
    void error(const std::exception &error,bool outcome=false,bool diagnostic=false) {std::lock_guard lock(mutex);if(phase=="setup")setup_failed=true;if(diagnostic)bump("phaseDiagnosticFailures");std::string category="failed",name=typeid(error).name();if(const auto *v=dynamic_cast<const public_failure_t*>(&error)){name=v->error_namespace+"."+v->public_name;++language[name];category=v->terminal;}else if(const auto *v=dynamic_cast<const validation_error*>(&error)){++harness[v->kind];name=v->kind;if(v->kind=="CorrelationExpired")category="timeout";}else if(const auto *v=dynamic_cast<const fw::framework_exception_t*>(&error)){const auto kind=v->kind();static constexpr const char *names[]={"NotFound","AlreadyExists","TypeMismatch","NotConfigured","Rejected","Unavailable","DeadlineExceeded","ShuttingDown","ProtocolError","InvalidOperation","DataLost","InternalFailure"};name=names[static_cast<int>(kind)];++by_kind[name];if(kind==fw::framework_error_kind_t::deadline_exceeded||v->code()==std::errc::timed_out)category="timeout";if(v->code()==std::errc::operation_canceled)category="cancelled";}else{++language[name];if(const auto *v=dynamic_cast<const std::system_error*>(&error)){if(v->code()==std::errc::timed_out)category="timeout";if(v->code()==std::errc::operation_canceled)category="cancelled";}}if(outcome)bump("messages."+category);if(errors.size()<32){json observation={{"type",name},{"message",error.what()}};if(const auto *v=dynamic_cast<const public_failure_t*>(&error)){observation["publicErrorNamespace"]=v->error_namespace;observation["publicErrorCode"]=v->code;observation["publicErrorName"]=v->public_name;}errors.push_back(std::move(observation));}}
    void finish(const std::shared_ptr<operation_t> &op,const std::exception *failure=nullptr,std::int64_t at=ticks()) {std::lock_guard lock(mutex);if(!op||op->done||sealed)return;op->done=true;--inflight;operations.erase(op->request.fields.at("correlationId"));if(failure)error(*failure,true);else if(!config.send()&&!config.publish()){bump(at<end?"messages.completed":"messages.settleCompleted",1,at);record(at<end?"latencyMs":"settleLatencyMs",at-op->primary_started);if(at-op->primary_started<=config.workload().at("applicationDeadlineMs").get<std::int64_t>()*1000000){++slo_met;if(at<end)++slo_window_met;}}changed.notify_all();}
    void admission(const request_t &request,std::int64_t started) {std::lock_guard lock(mutex);if(sealed||!start)return;const auto at=ticks();if(!config.publish())bump("messages.admitted");bump(config.publish()?(at<end?"messages.publishedInWindow":"messages.settlePublished"):(at<end?"messages.admittedInWindow":"messages.settleAdmitted"),1,at);(at<end?window_admission:settle_admission).add(request.fields.at("clientId"),decimal(request.fields.at("sequence")));if(config.send())record("sendAdmissionLatencyMs",at-started,at);if(config.actor())record("sourceAdmissionMs",at-started,at);}
    void delivered(const request_t &request) {std::lock_guard lock(mutex);if(sealed||request.fields.at("phase")=="warmup")return;const int stream=request.fields.at("clientId");const auto seq=decimal(request.fields.at("sequence"));if(all_delivery.add(stream,seq))(ticks()<end?window_delivery:settle_delivery).add(stream,seq);}
    void correlate(const std::shared_ptr<operation_t> &op) {std::lock_guard lock(mutex);pending.emplace(op->request.fields.at("correlationId"),op);}
    void receive_reply(const reply_t &reply) {std::lock_guard lock(mutex);const std::string id=reply.fields.at("correlationId");auto found=pending.find(id);if(found==pending.end()){auto previous=terminal.find(id);bump(previous==terminal.end()?"messages.unknownCorrelation":previous->second?"messages.duplicateReply":"messages.lateReply");return;}auto op=found->second;try{validate_reply(op->request,reply);finish(op);terminal[id]=true;}catch(const std::exception &failure){finish(op,&failure);terminal[id]=false;}pending.erase(found);}
    void expire() {std::lock_guard lock(mutex);const auto at=ticks();for(auto it=pending.begin();it!=pending.end();){auto op=it->second;if(at-op->primary_started>=config.workload().at("correlationExpiryMs").get<std::int64_t>()*1000000){validation_error failure("CorrelationExpired","Application echo correlation expired.");bump("messages.expired");finish(op,&failure,at);terminal[it->first]=false;it=pending.erase(it);}else ++it;}}
    void prepare_histograms(){
        if(primary&&!config.send()&&!config.publish()){hist.try_emplace("latencyMs");hist.try_emplace("settleLatencyMs");}
        if(config.worker())for(const auto *key:{"workerCallLatencyMs","workerTaskLatencyMs","workerSubmitToStartMs","workerResultToContinuationMs"})hist.try_emplace(key);
        if(primary&&config.driven())hist.try_emplace("driverLatencyMs");
        if(primary&&config.send())hist.try_emplace("sendAdmissionLatencyMs");
    }
    json trigger(const json &request) {std::lock_guard lock(mutex);auto ack=request;ack["configHash"]=config.value.at("configHash");ack["accepted"]=false;ack["state"]="rejected";ack["reason"]="Identity, phase or drain mismatch.";const std::string p=request.value("phase","");if(request.value("runId","")!=config.text("runId")||request.value("cellId","")!=config.text("cellId")||request.value("resetSeq","")!=reset_seq||(p!="warmup"&&p!="measured"))return ack;const auto key=p+"/"+reset_seq;if(starts.contains(key)){auto old=starts.at(key);old["state"]="alreadyStarted";return old;}if(running||inflight||active||(p=="warmup"&&phase!="setup")||(p=="measured"&&phase!="reset"))return ack;prepare_histograms();phase=p;start=ticks();end=start+static_cast<std::int64_t>(config.workload().at(p=="warmup"?"warmupSeconds":"durationSeconds").get<double>()*1e9);start_unix=unix_ms();running=true;sealed=false;sample_ticks=0;sample(true);cpu_start_ns=sample_cpu_ns;cpu_started=cpu_start_ns/1e9;ack["accepted"]=true;ack["state"]="started";ack["reason"]=nullptr;starts.emplace(key,ack);changed.notify_all();return ack;}
    void end_window() {std::lock_guard lock(mutex);if(phase!="settle"){phase="settle";end_unix=unix_ms();sample(true);cpu_used=(sample_cpu_ns-cpu_start_ns)/1e9;}}
    void complete() {std::lock_guard lock(mutex);if(inflight||active){validation_error failure("SettleIncomplete","Application cohort did not drain within fixed settle bound.");error(failure);}counts["messages.unresolved"]=inflight;settled=ticks();sealed=true;running=false;phase="complete";changed.notify_all();}
    json reset(const json &request,fw::framework_runtime_t *runtime=nullptr) {std::unique_lock lock(mutex);std::string why;if(request.value("runId","")!=config.text("runId")||request.value("cellId","")!=config.text("cellId"))why="Different run/cell.";else if(decimal(request.at("resetSeq"))<=std::stoull(reset_seq))why="resetSeq must advance.";else if(running||inflight||active||phase!="complete")why="Previous phase has not drained.";else if(setup_failed)why="Setup failed.";else if(!harness.empty()||counts["phaseDiagnosticFailures"]||counts["load.lateWarmupMessages"])why="Previous instrumentation or phase failed.";json ack={{"ok",why.empty()},{"runId",config.value.at("runId")},{"cellId",config.value.at("cellId")},{"resetSeq",request.at("resetSeq")},{"role",config.value.at("role")},{"roleInstance",config.value.at("roleInstance")},{"applicationResetAtUnixMs",unix_ms()},{"capacityEpoch",nullptr},{"reason",why.empty()?json(nullptr):json(why)},{"nullReasons",json::object()}};if(!why.empty())return ack;
        counts.clear();by_kind.clear();harness.clear();language.clear();hist.clear();bins.clear();cpu_bins.clear();cpu_samples=json::array();sample_ticks=0;sample_cpu_ns=cpu_start_ns=0;attempted={};window_admission={};settle_admission={};window_delivery={};settle_delivery={};all_delivery={};terminal.clear();public_samples=json::array();public_metrics=json::array();errors=json::array();worker_observation=nullptr;slo_met=slo_window_met=rss_peak=max_inflight=0;start=end=settled=0;start_unix=end_unix=nullptr;cpu_used=0;sealed=false;phase="reset";reset_seq=request.at("resetSeq");if(runtime){lock.unlock();runtime->reset_capacity_metrics();const auto epoch=runtime->status().capacity.measurement_epoch;lock.lock();ack["capacityEpoch"]=std::to_string(epoch);}else ack["nullReasons"]["/capacityEpoch"]=reason("NOT_APPLICABLE","Client has no Framework host.");reset_ack=ack;return ack;}
    json snapshot(json status=nullptr) {std::lock_guard lock(mutex);json metrics=json::object(),histograms=json::object(),nulls=json::object();const auto fixture=read_json(std::string(ZLINK_PERF_CONTRACT_DIR)+"/metric-catalog.json");
        auto nil=[&](const std::string &key,std::string code="NOT_APPLICABLE",std::string why="No corresponding public observation for this role/scenario."){metrics[key]=nullptr;nulls["/metrics/"+key]=reason(code,why);};auto count=[&](const std::string &key){return counts[key];};auto set=[&](const std::string &key,json value){metrics[key]=std::move(value);nulls.erase("/metrics/"+key);};
        for(const auto *family:{"counts","rates","unsupported"})for(const std::string key:fixture.at(family))nil(key,family==std::string("unsupported")?"PUBLIC_OBSERVATION_UNSUPPORTED":"NOT_APPLICABLE");for(const std::string prefix:fixture.at("latencyPrefixes"))for(const std::string suffix:fixture.at("latencySuffixes"))nil(prefix+"."+suffix);
        for(const auto &[key,prefixValue]:fixture.at("histogramPrefixes").items()){const std::string prefix=prefixValue;auto found=hist.find(key);if(found==hist.end()){histograms[key]=nullptr;const bool clock=(key.find("DeliveryLatency")!=std::string::npos&&(config.send()||config.publish()));nulls["/histograms/"+key]=reason(clock?"CLOCK_DOMAIN_UNVERIFIED":"NOT_APPLICABLE","Interval is unavailable or clock alignment is unverified.");if(clock)for(const std::string suffix:fixture.at("latencySuffixes"))nil(prefix+"."+suffix,"CLOCK_DOMAIN_UNVERIFIED");continue;}const auto &h=found->second;histograms[key]=h.snapshot();set(prefix+".meanMs",h.count?json(h.sum.convert_to<double>()/h.count/1e6):json(nullptr));set(prefix+".maxMs",h.count?json(h.max/1e6):json(nullptr));for(const auto &[suffix,numerator,denominator]:std::vector<std::tuple<std::string,int,int>>{{"p50Ms",50,100},{"p95Ms",95,100},{"p99Ms",99,100},{"p999Ms",999,1000}}){auto value=suffix=="p999Ms"&&h.count<100000?json(nullptr):h.percentile(numerator,denominator);if(value.is_null())nil(prefix+"."+suffix,suffix=="p999Ms"&&h.count<100000?"INSUFFICIENT_SAMPLES":!h.count?"NO_SAMPLES":"HISTOGRAM_OVERFLOW","No reliable percentile bucket.");else set(prefix+"."+suffix,value);}if(!h.count){nil(prefix+".meanMs","NO_SAMPLES");nil(prefix+".maxMs","NO_SAMPLES");nulls["/histograms/"+key+"/maxNs"]=reason("NO_SAMPLES","No observations.");}}
        if(primary&&config.driven()&&!config.send()&&!config.correlated())for(const std::string suffix:fixture.at("latencySuffixes")){const auto source="latency."+suffix,target="spot.remoteCallLatency."+suffix;if(metrics.at(source).is_null())nil(target,nulls.at("/metrics/"+source).at("code"),"Same interval and samples as primary latencyMs.");else set(target,metrics.at(source));}
        for(const auto &[key,value]:counts)if(key!="phaseDiagnosticFailures")set(key,std::to_string(value));for(const std::string key:{"request","send","reply","event"}){set("applicationMessages."+key,std::to_string(count("applicationMessages."+key)));set("applicationPayloadBytes."+key,std::to_string(count("applicationPayloadBytes."+key)));}set("load.lateWarmupMessages",std::to_string(count("load.lateWarmupMessages")));
        if(primary){for(const std::string key:{"sent","failed","timeout","cancelled","unresolved"})set("messages."+key,std::to_string(key=="unresolved"&&!sealed?inflight:count("messages."+key)));if(!config.send()&&!config.publish())for(const std::string key:{"completed","settleCompleted"})set("messages."+key,std::to_string(count("messages."+key)));set("load.inflight.max",std::to_string(max_inflight));set("load.inflightPerStream",std::to_string(config.workload().at("inflight").get<int>()));if(!config.cs())set("load.logicalStreams",std::to_string(config.workload().value("logicalStreams",json(1)).is_number()?config.workload().at("logicalStreams").get<int>():1));}
        if(primary&&(config.send()||config.correlated())){set("messages.admitted",std::to_string(window_admission.count()+settle_admission.count()));set("messages.admittedInWindow",std::to_string(window_admission.count()));set("messages.settleAdmitted",std::to_string(settle_admission.count()));}if(primary&&config.correlated())for(const std::string key:{"expired","duplicateReply","lateReply","unknownCorrelation"})set("messages."+key,std::to_string(count("messages."+key)));
        const double seconds=start?(end-start)/1e9:0;std::uint64_t total_messages=0,total_bytes=0;for(const std::string key:{"request","send","reply","event"}){total_messages+=count("applicationMessages."+key);total_bytes+=count("applicationPayloadBytes."+key);}if(seconds){set("throughput.messagesPerSec",total_messages/seconds);set("throughput.megabytesPerSec",total_bytes/seconds/1048576);if(primary&&!config.send()&&!config.publish())set("throughput.kops",count("messages.completed")/seconds/1000);if(end_unix!=nullptr){set("process.cpuPercent",cpu_used/seconds*100);set("process.rssMb",rss_peak/1048576.0);}}
        if(primary&&!config.send()&&!config.publish()){const auto eligible=count("messages.sent");set("slo.eligible",std::to_string(eligible));set("slo.met",std::to_string(slo_met));set("slo.missed",std::to_string(eligible-slo_met));if(eligible)set("slo.missRatio",static_cast<double>(eligible-slo_met)/eligible);else nil("slo.missRatio","ZERO_DENOMINATOR");if(seconds)set("slo.goodputOpsPerSec",slo_window_met/seconds);}else if(config.send()||config.publish())for(const std::string key:{"eligible","met","missed","missRatio","goodputOpsPerSec"})nil("slo."+key,"CLOCK_DOMAIN_UNVERIFIED");
        if(primary&&config.send()&&seconds)set("send.admissionOpsPerSec",window_admission.count()/seconds);if(config.publish()){set("fanout.subscriberCount",std::to_string(config.workload().at("subscriberCount").get<int>()));if(primary){set("messages.published",std::to_string(window_admission.count()+settle_admission.count()));set("messages.publishedInWindow",std::to_string(window_admission.count()));set("messages.settlePublished",std::to_string(settle_admission.count()));if(seconds)set("fanout.publishOpsPerSec",window_admission.count()/seconds);}else{set("fanout.uniqueDelivered",std::to_string(all_delivery.count()));set("fanout.deliveredInWindow",std::to_string(window_delivery.count()));set("fanout.settleDelivered",std::to_string(settle_delivery.count()));std::uint64_t duplicates=0;for(auto [id,n]:all_delivery.duplicates)duplicates+=n;set("fanout.duplicateEvents",std::to_string(duplicates));set("fanout.outOfCohortEvents",std::to_string(count("fanout.outOfCohortEvents")));if(seconds)set("fanout.deliveryOpsPerSec",window_delivery.count()/seconds);}}
        if(config.cs()&&config.text("role")=="client"){set("connections.requested",std::to_string(requested_connections));set("connections.connected",std::to_string(connected));set("connections.failed",std::to_string(connection_failures));}for(const auto *family:{"byKind","harness","language"}){json object=json::object();const auto &map=std::string(family)=="byKind"?by_kind:std::string(family)=="harness"?harness:language;for(auto[key,n]:map)object[key]=std::to_string(n);set(std::string("errors.")+family,object);}
        for(const std::string key:{"process.allocatedMb","gc.gen0","gc.gen1","gc.gen2"})nil(key,"PUBLIC_OBSERVATION_UNSUPPORTED","C++ has no public equivalent cumulative allocation/generation counter.");
        json window={{"startedAtUnixMs",start_unix},{"endedAtUnixMs",end_unix},{"startTicks",start?json(std::to_string(start)):json(nullptr)},{"endTicks",end?json(std::to_string(end)):json(nullptr)},{"measuredSeconds",seconds?json(seconds):json(nullptr)},{"settleSeconds",settled?json(std::max(0.0,(settled-end)/1e9)):json(nullptr)}};for(auto[key,value]:window.items())if(value.is_null())nulls["/window/"+key]=reason("PHASE_NOT_STARTED","Window/settle not completed.");
        json clock={{"source","std::chrono::steady_clock"},{"nativeFrequencyHz","1000000000"},{"ticksUnit","ns"},{"clockDomainId",domain},{"scope","process"},{"alignmentMethod",nullptr},{"maxErrorNs",nullptr},{"validFromTicks",nullptr},{"validThroughTicks",nullptr},{"evidence",json::array({"Caller RTT and task duration use one process clock; no process clock alignment."})}};for(const std::string key:{"alignmentMethod","maxErrorNs","validFromTicks","validThroughTicks"})nulls["/clock/"+key]=reason("NOT_APPLICABLE","No cross-process alignment claim.");if(status.is_null())nulls["/publicStatus"]=reason("NOT_APPLICABLE","No Framework host in connector client.");
        json serialized=json::array({{{"direction",config.publish()?"event":config.send()||config.correlated()?"send":"request"},{"packetName",config.publish()?"PerfPublishEvent":"PerfEchoRequest"},{"logicalPayloadBytes",std::to_string(config.request_bytes())},{"observedSerializedBytes",nullptr}}});if(!config.send()&&!config.publish())serialized.push_back({{"direction",config.correlated()?"send":"reply"},{"packetName","PerfEchoReply"},{"logicalPayloadBytes",std::to_string(config.workload().at("responsePayloadBytes").get<int>())},{"observedSerializedBytes",nullptr}});for(std::size_t i=0;i<serialized.size();++i)nulls["/serializedMessageBytes/"+std::to_string(i)+"/observedSerializedBytes"]=reason("PUBLIC_OBSERVATION_UNSUPPORTED","No public serializer byte observation.");
        auto wrapper=[](std::string name,std::string type,json value){return json{{"name",name},{"unit","observation"},{"type",type},{"value",value}};};json source=json::array(),delivery=json::array();for(const auto &[id,ranges]:attempted.values)source.push_back({{"clientId",id},{"attemptedRanges",attempted.stream(id)},{"windowAdmissionRanges",window_admission.stream(id)},{"settleAdmissionRanges",settle_admission.stream(id)}});for(const auto &[id,ranges]:all_delivery.values)delivery.push_back({{"clientId",id},{"windowRanges",window_delivery.stream(id)},{"settleRanges",settle_delivery.stream(id)},{"duplicateCount",std::to_string(all_delivery.duplicates[id])}});json runtime={{"setupEvidence",wrapper("setupEvidence","array",setup)},{"errors",wrapper("firstErrors","array",errors)},{"sourceEvidence",wrapper("sourceEvidence","array",source)},{"deliveryEvidence",wrapper("deliveryEvidence","array",delivery)},{"publicReadinessSamples",wrapper("public host readiness and pressure samples","array",public_samples)},{"activeHandlers",{{"name","application active handlers"},{"unit","count"},{"type","integer"},{"value",std::to_string(active)}}}};if(!worker_observation.is_null())runtime["workerObservation"]=wrapper("workerObservation","object",worker_observation);if(config.publish()){if(primary)runtime["publisherSequences"]=wrapper("publisherSequences","object",{{"runId",config.value.at("runId")},{"cellId",config.value.at("cellId")},{"resetSeq",reset_seq},{"phase",reset_seq=="0"?"warmup":"measured"},{"attemptedRanges",attempted.stream(0)},{"windowSuccessRanges",window_admission.stream(0)},{"settleSuccessRanges",settle_admission.stream(0)}});else runtime["subscriberSequences"]=wrapper("subscriberSequences","object",{{"runId",config.value.at("runId")},{"cellId",config.value.at("cellId")},{"resetSeq",reset_seq},{"phase",reset_seq=="0"?"warmup":"measured"},{"subscriberId",config.value.at("roleInstance")},{"windowRanges",window_delivery.stream(0)},{"settleRanges",settle_delivery.stream(0)},{"duplicateEvents",std::to_string(all_delivery.duplicates[0])},{"timingEvidence",nullptr},{"nullReasons",{{"/timingEvidence",reason("CLOCK_DOMAIN_UNVERIFIED","No verified publisher/subscriber clock domain.")}}}});}
        runtime["cpuSamples"]=wrapper("cpuSamples","array",cpu_samples);runtime["phaseDiagnosticFailures"]={{"name","phaseDiagnosticFailures"},{"unit","count"},{"type","integer"},{"value",std::to_string(count("phaseDiagnosticFailures"))}};
        auto provenance=config.value.at("provenance");provenance["pid"]=getpid();provenance["configHash"]=config.value.at("configHash");provenance["resetAcknowledgement"]=reset_ack;provenance["primaryEchoOwner"]=primary&&!config.send()&&!config.publish();provenance["affinityProcessorCount"]=affinity_processors();provenance["logicalProcessorCount"]=std::max(1u,std::thread::hardware_concurrency());provenance["effectiveProcessorCount"]=status.is_null()?json(affinity_processors()):status.at("host").at("capacity").at("applicationJobQueue").at("effectiveProcessorCount");provenance["messageCountScope"]="application-call-boundaries";
        return {{"schemaVersion",3},{"runId",config.value.at("runId")},{"cellId",config.value.at("cellId")},{"configHash",config.value.at("configHash")},{"comparisonKey",provenance.value("comparisonKey",config.text("configHash"))},{"resetSeq",reset_seq},{"language","cpp"},{"role",config.value.at("role")},{"roleInstance",config.value.at("roleInstance")},{"phase",phase},{"window",window},{"clock",clock},{"serializedMessageBytes",serialized},{"metrics",metrics},{"histograms",histograms},{"nullReasons",nulls},{"publicStatus",status},{"publicMetrics",public_metrics},{"timeSeries",time_series()},{"runtimeMetrics",runtime},{"provenance",provenance}};
    }
};
struct handler_scope_t {measurement_t &measurement;explicit handler_scope_t(measurement_t &value):measurement(value){std::lock_guard lock(measurement.mutex);++measurement.active;}~handler_scope_t(){std::lock_guard lock(measurement.mutex);--measurement.active;measurement.changed.notify_all();}};
}
