/* SPDX-License-Identifier: MPL-2.0 */

#ifndef __ZLINK_ENUM_H_INCLUDED__
#define __ZLINK_ENUM_H_INCLUDED__

#include <stdint.h>

typedef enum zlink_ctx_option_t
{
    ZLINK_IO_THREADS = 1,
    ZLINK_MAX_SOCKETS = 2,
    ZLINK_SOCKET_LIMIT = 3,
    ZLINK_THREAD_PRIORITY = 3,
    ZLINK_THREAD_SCHED_POLICY = 4,
    ZLINK_MAX_MSGSZ = 5,
    ZLINK_MSG_T_SIZE = 6,
    ZLINK_THREAD_AFFINITY_CPU_ADD = 7,
    ZLINK_THREAD_AFFINITY_CPU_REMOVE = 8,
    ZLINK_THREAD_NAME_PREFIX = 9,
    ZLINK_CTX_OPT_BLOCKY = 10,
    ZLINK_CTX_OPT_AUTO_HWM_ENABLE = 12,
    ZLINK_CTX_OPT_AUTO_HWM_RECALC_DEBOUNCE_MS = 14,
    ZLINK_CTX_OPT_AUTO_HWM_PROFILE = 17,
    /* uint64_t bytes; use zlink_ctx_set_data()/zlink_ctx_get_data(). */
    ZLINK_CTX_OPT_AUTO_HWM_MSG_UNIT_BYTES = 18
} zlink_ctx_option_t;

typedef enum zlink_auto_hwm_profile_t
{
    ZLINK_AUTO_HWM_PROFILE_COMPACT = 0,
    ZLINK_AUTO_HWM_PROFILE_LOW_LATENCY = 1,
    ZLINK_AUTO_HWM_PROFILE_BALANCED = 2,
    ZLINK_AUTO_HWM_PROFILE_THROUGHPUT = 3
} zlink_auto_hwm_profile_t;

typedef enum zlink_socket_type_t
{
    ZLINK_SOCKET_ANY = 0,
    ZLINK_SOCKET_PAIR = 0x1001,
    ZLINK_SOCKET_PUB = 0x1002,
    ZLINK_SOCKET_SUB = 0x1003,
    ZLINK_SOCKET_DEALER = 0x1004,
    ZLINK_SOCKET_ROUTER = 0x1005,
    ZLINK_SOCKET_XPUB = 0x1006,
    ZLINK_SOCKET_XSUB = 0x1007,
    ZLINK_SOCKET_STREAM = 0x1008
} zlink_socket_type_t;

typedef enum zlink_option_t
{
    /* Queue, buffer, and message size options */
    ZLINK_OPT_AFFINITY = 0x3001,
    ZLINK_OPT_RATE = 0x3003,
    ZLINK_OPT_RECOVERY_IVL = 0x3004,
    ZLINK_OPT_SNDBUF = 0x3005,
    ZLINK_OPT_RCVBUF = 0x3006,
    ZLINK_OPT_MAXMSGSIZE = 0x300E,
    /* uint64_t directional pipe bytes; 0 means unlimited. */
    ZLINK_OPT_SNDHWM = 0x300F,
    ZLINK_OPT_RCVHWM = 0x3010,

    /* Lifecycle, timeout, and reconnect options */
    ZLINK_OPT_LINGER = 0x300A,
    ZLINK_OPT_RECONNECT_IVL = 0x300B,
    ZLINK_OPT_BACKLOG = 0x300C,
    ZLINK_OPT_RECONNECT_IVL_MAX = 0x300D,
    ZLINK_OPT_MULTICAST_HOPS = 0x3011,
    ZLINK_OPT_RCVTIMEO = 0x3012,
    ZLINK_OPT_SNDTIMEO = 0x3013,
    ZLINK_OPT_CONNECT_TIMEOUT = 0x3024,
    ZLINK_OPT_HANDSHAKE_IVL = 0x301D,

    /* TCP keepalive and transport-level TCP options */
    ZLINK_OPT_TCP_KEEPALIVE = 0x3015,
    ZLINK_OPT_TCP_KEEPALIVE_CNT = 0x3016,
    ZLINK_OPT_TCP_KEEPALIVE_IDLE = 0x3017,
    ZLINK_OPT_TCP_KEEPALIVE_INTVL = 0x3018,
    ZLINK_OPT_TCP_MAXRT = 0x3025,
    ZLINK_OPT_TCP_NODELAY = 0x3031,


    /* Network and address-family options */
    ZLINK_OPT_IPV6 = 0x301A,
    ZLINK_OPT_TOS = 0x301C,
    ZLINK_OPT_MULTICAST_MAXTPDU = 0x3026,
    ZLINK_OPT_BINDTODEVICE = 0x3027,
    ZLINK_OPT_TLS_CERT = 0x3028,
    ZLINK_OPT_TLS_KEY = 0x3029,
    ZLINK_OPT_TLS_CA = 0x302A,
    ZLINK_OPT_TLS_VERIFY = 0x302B,
    ZLINK_OPT_TLS_REQUIRE_CLIENT_CERT = 0x302C,
    ZLINK_OPT_TLS_HOSTNAME = 0x302D,
    ZLINK_OPT_TLS_TRUST_SYSTEM = 0x302E,
    ZLINK_OPT_TLS_PASSWORD = 0x302F,

    /* Delivery, buffering policy, and filter semantics */
    ZLINK_OPT_IMMEDIATE = 0x3019,
    ZLINK_OPT_CONFLATE = 0x301B,
    ZLINK_OPT_BLOCKY = 0x301E,
    ZLINK_OPT_INVERT_MATCHING = 0x3020,
    ZLINK_OPT_SUBMIT_RETRY_MODE = 0x3037,
    ZLINK_OPT_SUBMIT_RETRY_TIMEOUT = 0x3038,
    ZLINK_OPT_SUBMIT_RETRY_ATTEMPTS = 0x3039,

    /* Introspection and protocol metadata */
    ZLINK_OPT_FD = 0x3007,
    ZLINK_OPT_EVENTS = 0x3008,
    ZLINK_OPT_TYPE = 0x3009,
    ZLINK_OPT_LAST_ENDPOINT = 0x3014,
    ZLINK_OPT_ZMP_METADATA = 0x3030,
    ZLINK_OPT_ROUTE_VALUE_MAX_SIZE = 0x3032,
    ZLINK_OPT_RID_DUPLICATE_POLICY = 0x3033,
    /* uint64_t Auto HWM planning-unit bytes; 0 selects the default. */
    ZLINK_OPT_AUTO_HWM_MSG_UNIT_BYTES = 0x3034
} zlink_option_t;

typedef enum zlink_submit_retry_mode_t
{
    ZLINK_SUBMIT_RETRY_OFF = 0,
    ZLINK_SUBMIT_RETRY_LOCAL_FAILURE = 1
} zlink_submit_retry_mode_t;

typedef enum zlink_rid_duplicate_policy_t
{
    ZLINK_RID_DUPLICATE_REJECT = 0,
    ZLINK_RID_DUPLICATE_HANDOVER = 1
} zlink_rid_duplicate_policy_t;

typedef enum zlink_router_option_t
{
    ZLINK_ROUTER_OPT_MANDATORY = 0x3101,
    ZLINK_ROUTER_OPT_PROBE = 0x3103,
    ZLINK_ROUTER_OPT_CONNECT_ROUTING_ID = 0x3104,
    ZLINK_ROUTER_OPT_REQUEST_TIMEOUT_MS = 0x3105,
    ZLINK_ROUTER_OPT_WEIGHT = 0x3106
} zlink_router_option_t;

typedef enum zlink_dealer_option_t
{
    ZLINK_DEALER_OPT_PROBE = 0x3201,
    ZLINK_DEALER_OPT_REQUEST_TIMEOUT_MS = 0x3202,
    ZLINK_DEALER_OPT_WEIGHT = 0x3203
} zlink_dealer_option_t;

typedef enum zlink_dealer_message_type_t
{
    ZLINK_DEALER_MESSAGE_RAW = 0,
    ZLINK_DEALER_MESSAGE_REQUEST = 1,
    ZLINK_DEALER_MESSAGE_REPLY = 2,
    ZLINK_DEALER_MESSAGE_ERROR_REPLY = 3
} zlink_dealer_message_type_t;

typedef enum zlink_pub_option_t
{
    ZLINK_PUB_OPT_VERBOSE = 0x3301,
    ZLINK_PUB_OPT_VERBOSER = 0x3302,
    ZLINK_PUB_OPT_MANUAL = 0x3303,
    ZLINK_PUB_OPT_MANUAL_LAST_VALUE = 0x3304,
    ZLINK_PUB_OPT_NODROP = 0x3305,
    ZLINK_PUB_OPT_WELCOME_MSG = 0x3306,
    ZLINK_PUB_OPT_TOPICS_COUNT = 0x3307,
    ZLINK_PUB_OPT_APPROVE_SUBSCRIBE = 0x3308,
    ZLINK_PUB_OPT_REJECT_SUBSCRIBE = 0x3309
} zlink_pub_option_t;

typedef enum zlink_sub_option_t
{
    ZLINK_SUB_OPT_TOPICS_COUNT = 0x3400
} zlink_sub_option_t;

typedef enum zlink_stream_option_t
{
    ZLINK_STREAM_OPT_NOTIFY = 0x3501
} zlink_stream_option_t;

typedef enum zlink_disconnect_reason_t
{
    ZLINK_DISCONNECT_REASON_UNKNOWN = 0,
    ZLINK_DISCONNECT_REASON_HANDSHAKE_FAILED = 3,
    ZLINK_DISCONNECT_REASON_TRANSPORT_ERROR = 4,
    ZLINK_DISCONNECT_REASON_CTX_TERM = 5
} zlink_disconnect_reason_t;

typedef enum zlink_auto_hwm_recalc_reason_t
{
    ZLINK_AUTO_HWM_RECALC_REASON_NONE = 0,
    ZLINK_AUTO_HWM_RECALC_REASON_INITIAL = 1,
    ZLINK_AUTO_HWM_RECALC_REASON_ROLE_CHANGE = 2,
    ZLINK_AUTO_HWM_RECALC_REASON_POLICY_TOGGLE = 3,
    ZLINK_AUTO_HWM_RECALC_REASON_REFRESH = 4,
    ZLINK_AUTO_HWM_RECALC_REASON_DEFERRED_SHRINK = 5
} zlink_auto_hwm_recalc_reason_t;

typedef enum zlink_protocol_error_t
{
    ZLINK_PROTOCOL_ERROR_ZMP_MALFORMED_COMMAND_HELLO = 0x10000013
} zlink_protocol_error_t;

typedef enum zlink_monitor_source_kind_t
{
    ZLINK_MONITOR_SOURCE_SOCKET = 1
} zlink_monitor_source_kind_t;

typedef uint32_t zlink_socket_monitor_event_mask_t;

typedef enum zlink_socket_monitor_event_e
{
    ZLINK_SOCKET_MONITOR_EVENT_CONNECTED = 1u << 0,
    ZLINK_SOCKET_MONITOR_EVENT_CONNECT_DELAYED = 1u << 1,
    ZLINK_SOCKET_MONITOR_EVENT_CONNECT_RETRIED = 1u << 2,
    ZLINK_SOCKET_MONITOR_EVENT_LISTENING = 1u << 3,
    ZLINK_SOCKET_MONITOR_EVENT_BIND_FAILED = 1u << 4,
    ZLINK_SOCKET_MONITOR_EVENT_ACCEPTED = 1u << 5,
    ZLINK_SOCKET_MONITOR_EVENT_ACCEPT_FAILED = 1u << 6,
    ZLINK_SOCKET_MONITOR_EVENT_CLOSED = 1u << 7,
    ZLINK_SOCKET_MONITOR_EVENT_CLOSE_FAILED = 1u << 8,
    ZLINK_SOCKET_MONITOR_EVENT_DISCONNECTED = 1u << 9,
    ZLINK_SOCKET_MONITOR_EVENT_MONITOR_STOPPED = 1u << 10,
    ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_NO_DETAIL = 1u << 11,
    ZLINK_SOCKET_MONITOR_EVENT_CONNECTION_READY = 1u << 12,
    ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_PROTOCOL = 1u << 13,
    ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_AUTH = 1u << 14,
    ZLINK_SOCKET_MONITOR_EVENT_PEER_WEIGHT_CHANGED = 1u << 15,
    ZLINK_SOCKET_MONITOR_EVENT_ALL = 0xFFFFu,

    ZLINK_EVENT_CONNECTED = ZLINK_SOCKET_MONITOR_EVENT_CONNECTED,
    ZLINK_EVENT_CONNECT_DELAYED = ZLINK_SOCKET_MONITOR_EVENT_CONNECT_DELAYED,
    ZLINK_EVENT_CONNECT_RETRIED = ZLINK_SOCKET_MONITOR_EVENT_CONNECT_RETRIED,
    ZLINK_EVENT_LISTENING = ZLINK_SOCKET_MONITOR_EVENT_LISTENING,
    ZLINK_EVENT_BIND_FAILED = ZLINK_SOCKET_MONITOR_EVENT_BIND_FAILED,
    ZLINK_EVENT_ACCEPTED = ZLINK_SOCKET_MONITOR_EVENT_ACCEPTED,
    ZLINK_EVENT_ACCEPT_FAILED = ZLINK_SOCKET_MONITOR_EVENT_ACCEPT_FAILED,
    ZLINK_EVENT_CLOSED = ZLINK_SOCKET_MONITOR_EVENT_CLOSED,
    ZLINK_EVENT_CLOSE_FAILED = ZLINK_SOCKET_MONITOR_EVENT_CLOSE_FAILED,
    ZLINK_EVENT_DISCONNECTED = ZLINK_SOCKET_MONITOR_EVENT_DISCONNECTED,
    ZLINK_EVENT_MONITOR_STOPPED = ZLINK_SOCKET_MONITOR_EVENT_MONITOR_STOPPED,
    ZLINK_EVENT_HANDSHAKE_FAILED_NO_DETAIL = ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_NO_DETAIL,
    ZLINK_EVENT_CONNECTION_READY = ZLINK_SOCKET_MONITOR_EVENT_CONNECTION_READY,
    ZLINK_EVENT_HANDSHAKE_FAILED_PROTOCOL = ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_PROTOCOL,
    ZLINK_EVENT_HANDSHAKE_FAILED_AUTH = ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_AUTH,
    ZLINK_EVENT_PEER_WEIGHT_CHANGED = ZLINK_SOCKET_MONITOR_EVENT_PEER_WEIGHT_CHANGED,
    ZLINK_EVENT_ALL = ZLINK_SOCKET_MONITOR_EVENT_ALL
} zlink_socket_monitor_event_e;

typedef uint32_t zlink_monitor_state_mask_t;
typedef uint32_t zlink_monitor_status_detail_mask_t;

typedef enum zlink_monitor_state_flag_e
{
    ZLINK_MONITOR_STATE_READY = 1u << 0,
    ZLINK_MONITOR_STATE_BOUND_READY = 1u << 1,
    ZLINK_MONITOR_STATE_CLOSED = 1u << 3
} zlink_monitor_state_flag_e;

typedef enum zlink_monitor_status_detail_flag_e
{
    ZLINK_MONITOR_STATUS_DETAIL_SND_PENDING_MSGS = 1u << 1,
    ZLINK_MONITOR_STATUS_DETAIL_RCV_PENDING_MSGS = 1u << 2,
    ZLINK_MONITOR_STATUS_DETAIL_AUTO_HWM_BUDGET = 1u << 3,
    ZLINK_MONITOR_STATUS_DETAIL_AUTO_HWM_BUFFERS = 1u << 4
} zlink_monitor_status_detail_flag_e;

typedef enum zlink_poller_source_kind_t
{
    ZLINK_POLLER_SOURCE_SOCKET = 1,
    ZLINK_POLLER_SOURCE_FD = 2,
    ZLINK_POLLER_SOURCE_TIMER = 3
} zlink_poller_source_kind_t;

typedef enum zlink_send_flags_t
{
    ZLINK_SEND_FLAGS_NONE = 0,
    ZLINK_SEND_FLAGS_DONTWAIT = 0x0001u
} zlink_send_flags_t;

typedef enum zlink_recv_flags_t
{
    ZLINK_RECV_FLAGS_NONE = 0,
    ZLINK_RECV_FLAGS_DONTWAIT = 0x0001u
} zlink_recv_flags_t;

typedef short zlink_poller_event_mask_t;

typedef enum zlink_poller_event_flag_e
{
    ZLINK_POLLIN = 1,
    ZLINK_POLLOUT = 2,
    ZLINK_POLLERR = 4,
    ZLINK_POLLPRI = 8,
    ZLINK_POLLITEMS_DFLT = 16,
    ZLINK_POLLCOMPLETION = 32
} zlink_poller_event_flag_e;

#endif
