
file(READ "${PROJECT_SOURCE_DIR}/include/zlink.h" _ZLINK_H_CONTENTS)
string(REGEX REPLACE ".*#define ZLINK_VERSION_MAJOR ([0-9]+).*" "\\1" ZLINK_VERSION_MAJOR "${_ZLINK_H_CONTENTS}")
string(REGEX REPLACE ".*#define ZLINK_VERSION_MINOR ([0-9]+).*" "\\1" ZLINK_VERSION_MINOR "${_ZLINK_H_CONTENTS}")
string(REGEX REPLACE ".*#define ZLINK_VERSION_PATCH ([0-9]+).*" "\\1" ZLINK_VERSION_PATCH "${_ZLINK_H_CONTENTS}")
set(ZLINK_VERSION "${ZLINK_VERSION_MAJOR}.${ZLINK_VERSION_MINOR}.${ZLINK_VERSION_PATCH}")

message(STATUS "Detected ZLINK Version - ${ZLINK_VERSION}")
