#pragma once
#include "../Shared/measurement.hpp"
#include "../Shared/http.hpp"
#include <zlink/stream_connector.hpp>
#include <iostream>

namespace perf {
namespace sc=zlink::stream_connector;
class client_t {
    json manifest;int index;measurement_t &m;std::vector<std::shared_ptr<sc::connector_t>> connectors;std::vector<int> stream_ids;std::thread coordinator;std::atomic_bool stopping=false;std::vector<std::uint64_t> sequences;
    struct slot_t {std::size_t connector;std::shared_ptr<operation_t> op;};std::vector<slot_t> slots;
    static public_failure_t observation(const sc::error_t &error){static constexpr const char *names[]={"Disconnected","ConfigurationError","ValidationFailed","RequestTimeout","ConnectTimeout","FrameDecodeFailed","FrameTooLarge","SendFailed","UnsupportedCodec","CompressionFailed","TlsValidationFailed","DecompressionFailed","UserCallbackFailed","ObserverFailed","ObserverDropped","ReceivedMessageDropped","RemoteError","Closed","Canceled"};const auto code=static_cast<int>(error.code);const std::string category=error.code==sc::error_code_t::request_timeout||error.code==sc::error_code_t::connect_timeout?"timeout":error.code==sc::error_code_t::canceled?"cancelled":"failed";return public_failure_t("streamConnector",names[code],code,category,error.message);}
    void failure(const sc::error_t &error,bool outcome){m.error(observation(error),outcome);}
  public:
    client_t(json value,int client_index,measurement_t &measurement):manifest(std::move(value)),index(client_index),m(measurement){}
    ~client_t(){close();}
    void prepare(){std::vector<json> endpoints;for(const auto &role:manifest.at("roles"))if(role.contains("streamEndpoint")&&!role.at("streamEndpoint").is_null())endpoints.push_back(role);if(endpoints.empty())throw std::invalid_argument("CS endpoint manifest has no session listener.");const int total=m.config.workload().at("connections");const int clients=m.config.workload().at("clientCount");const int concurrency=m.config.workload().at("connectConcurrency");std::uint64_t pending=0,socket_connected=0,bound=0;
        for(int stream=index;stream<total;stream+=clients){const auto &role=endpoints.at(stream%endpoints.size());sc::connector_options_t options;options.endpoint=role.at("streamEndpoint");if(!options.endpoint.starts_with("ws://"))throw std::invalid_argument("CS comparison requires public WebSocket transport.");options.transport=sc::transport_t::websocket;options.connect_timeout=std::chrono::milliseconds(m.config.workload().at("setupTimeoutMs").get<int>());options.request_timeout=std::chrono::milliseconds(m.config.timeout());options.dispatch_mode=sc::dispatch_mode_t::immediate;options.diagnostics_level=m.config.diagnostics_enabled()?sc::diagnostics_level_t::normal:sc::diagnostics_level_t::off;
            auto connector=std::make_shared<sc::connector_t>(sc::connector_factory_t::create(std::move(options)));connectors.push_back(connector);stream_ids.push_back(stream);{std::unique_lock lock(m.mutex);m.changed.wait(lock,[&]{return pending<static_cast<std::uint64_t>(concurrency);});++pending;++m.requested_connections;}
            connector->connect([this,&pending,&socket_connected](sc::result_t<void> result){std::lock_guard lock(m.mutex);--pending;if(result)++socket_connected;else{++m.connection_failures;failure(*result.error(),false);}m.changed.notify_all();});}
        {std::unique_lock lock(m.mutex);m.changed.wait(lock,[&]{return pending==0;});}m.setup.push_back({{"kind","socketConnections"},{"source","public connector connect callbacks"},{"observedValue",{{"requested",std::to_string(m.requested_connections)},{"connected",std::to_string(socket_connected)},{"failed",std::to_string(m.connection_failures)}}}});if(m.connection_failures)throw std::runtime_error("CS preparation has connection failures.");
        if(m.config.actor()){for(std::size_t i=0;i<connectors.size();++i){auto connector=connectors[i];const auto &role=endpoints.at(stream_ids[i]%endpoints.size());const int actor_index=stream_ids[i]/endpoints.size();{std::unique_lock lock(m.mutex);m.changed.wait(lock,[&]{return pending<static_cast<std::uint64_t>(concurrency);});++pending;}
            connector->request(bind_t{{{"runId",m.config.value.at("runId")},{"cellId",m.config.value.at("cellId")},{"clientId",actor_index}}}).timeout(std::chrono::milliseconds(m.config.workload().at("setupTimeoutMs").get<int>())).submit<bind_reply_t>([this,&pending,&bound,role,actor_index](sc::result_t<bind_reply_t> result){std::lock_guard lock(m.mutex);--pending;try{if(!result){failure(*result.error(),false);}else if(!result.value().fields.at("bound").get<bool>()||result.value().fields.at("actorId")!=role.at("actorIds").at(actor_index))throw validation_error("IdentityMismatch","CS public bind reply differs.");else ++bound;}catch(const std::exception &error){m.error(error);}m.changed.notify_all();});}
            std::unique_lock lock(m.mutex);m.changed.wait(lock,[&]{return pending==0;});}
        if(connectors.empty())throw std::invalid_argument("CS client owns zero connections.");
        if(m.config.actor())m.setup.push_back({{"kind","actorBinds"},{"source","public typed bind reply validation"},{"observedValue",{{"requested",std::to_string(connectors.size())},{"bound",std::to_string(bound)}}}});
        if(!m.by_kind.empty()||!m.harness.empty()||!m.language.empty())throw std::runtime_error("CS actor bind preparation failed.");
        for(std::size_t i=0;i<connectors.size();++i){const auto request=m.request(stream_ids[i],0,true);{std::unique_lock lock(m.mutex);m.changed.wait(lock,[&]{return pending<static_cast<std::uint64_t>(concurrency);});++pending;}
            connectors[i]->request(request).timeout(std::chrono::milliseconds(m.config.workload().at("setupTimeoutMs").get<int>())).submit<reply_t>([this,&pending,request](sc::result_t<reply_t> result){std::lock_guard lock(m.mutex);--pending;try{if(!result){++m.connection_failures;failure(*result.error(),false);}else{m.validate_reply(request,result.value());++m.connected;}}catch(const std::exception &error){++m.connection_failures;m.error(error);}m.changed.notify_all();});}
        {std::unique_lock lock(m.mutex);m.changed.wait(lock,[&]{return pending==0;});}
        m.setup.push_back({{"kind","typedProbeEcho"},{"source","every public connector typed PerfEchoRequest/Reply and full reply validation"},{"observedValue",{{"requested",std::to_string(connectors.size())},{"validated",std::to_string(m.connected)},{"connectConcurrency",concurrency}}}});
        if(m.connected!=connectors.size())throw std::runtime_error("CS typed preparation probe failed.");
        sequences.resize(connectors.size());for(std::size_t c=0;c<connectors.size();++c)for(int i=0;i<m.config.workload().at("inflight").get<int>();++i)slots.push_back({c,{}});coordinator=std::thread([this]{coordinate();});
    }
    void coordinate(){try{while(!stopping){std::unique_lock lock(m.mutex);if(!m.running){m.changed.wait_for(lock,std::chrono::milliseconds(100));continue;}lock.unlock();for(auto &slot:slots){if((!slot.op||slot.op->done)&&m.can_issue()){const auto stream=stream_ids[slot.connector];auto op=m.begin(m.request(stream,++sequences[slot.connector]));slot.op=op;if(!op)continue;m.direction("request",m.config.request_bytes());connectors[slot.connector]->request(op->request).timeout(std::chrono::milliseconds(m.config.timeout())).submit<reply_t>([this,op](sc::result_t<reply_t> result){if(!result){const auto error=observation(*result.error());m.finish(op,&error);return;}try{m.validate_reply(op->request,result.value());m.finish(op);}catch(const std::exception &error){m.finish(op,&error);}});}}
        lock.lock();m.sample();const auto at=ticks();if(at>=m.end){m.end_window();if(!m.inflight||at>=m.end+m.config.workload().at("settleTimeoutMs").get<std::int64_t>()*1000000)m.complete();}m.changed.wait_for(lock,std::chrono::milliseconds(1));}}catch(const std::exception &error){m.error(error,false,true);m.complete();}}
    json roles(const json &request,bool reset){json answers=json::array();for(const auto &role:manifest.at("roles")){const std::string base=reset?role.at("metrics").at("baseUrl"):role.at("applicationTriggerUrl");answers.push_back(http_json(reset?base+"/perf/reset":base,"POST",request,m.config.workload().at("adminTimeoutMs")));}return {{"ok",true},{"acknowledgements",answers}};}
    void control(){std::cout<<json{{"type","prepared"},{"ok",m.by_kind.empty()&&m.harness.empty()&&m.language.empty()},{"snapshot",m.snapshot()}}.dump()<<std::endl;std::string line;while(std::getline(std::cin,line)){try{const auto command=json::parse(line);const std::string name=command.at("command");json response;if(name=="start")response=m.trigger(command.at("request"));else if(name=="reset"){response=m.reset(command.at("request"));std::fill(sequences.begin(),sequences.end(),0);}else if(name=="triggerRoles")response=roles(command.at("request"),false);else if(name=="resetRoles")response=roles(command.at("request"),true);else if(name=="wait"){std::unique_lock lock(m.mutex);m.changed.wait(lock,[&]{return !m.running;});response={{"ok",m.by_kind.empty()&&m.harness.empty()&&m.language.empty()},{"phase",m.phase}};}else if(name=="stats")response=m.snapshot();else if(name=="stop")break;else throw std::invalid_argument("Unknown control command.");std::cout<<json{{"ok",true},{"response",response}}.dump()<<std::endl;}catch(const std::exception &error){m.error(error,false,true);std::cout<<json{{"ok",false},{"errorType",typeid(error).name()},{"message",error.what()}}.dump()<<std::endl;}}}
    void close(){stopping=true;m.changed.notify_all();if(coordinator.joinable())coordinator.join();for(const auto &connector:connectors){auto result=connector->close();if(!result)failure(*result.error(),false);}connectors.clear();}
};
inline int run_client(const std::string &file,int index){const auto manifest=read_json(file);if(index<0||index>=manifest.at("workload").at("clientCount").get<int>())throw std::invalid_argument("Invalid client index.");json config={{"runId",manifest.at("runId")},{"cellId",manifest.at("cellId")},{"configHash",manifest.at("configHash")},{"role","client"},{"roleInstance",index},{"scenario",manifest.at("scenario")},{"mode",manifest.at("mode")},{"source",true},{"workload",manifest.at("workload")},{"provenance",manifest.at("provenance")},{"terminal","ordinary"},{"diagnostics",manifest.value("diagnostics",json(nullptr))}};measurement_t m(config_t{config},true);client_t client(manifest,index,m);client.prepare();client.control();return 0;}
}
