<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <TargetFrameworks>$(ZLinkFrameworkTargetFrameworks)</TargetFrameworks>
        <AssemblyName>Systems.Zlink.Stream.Connector</AssemblyName>
        <RootNamespace>Systems.Zlink.Stream.Connector</RootNamespace>
        <Description>ZLink STREAM client connector for .NET.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="K4os.Compression.LZ4"/>
    </ItemGroup>
</Project>
