<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>RegistrationCodec.Shared</AssemblyName>
        <RootNamespace>RegistrationCodec.Shared</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf"/>
        <PackageReference Include="Grpc.Tools" PrivateAssets="all"/>
        <PackageReference Include="MessagePack"/>
        <Protobuf Include="Contracts\registration_codec.proto" GrpcServices="None"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../src/Zlink.Framework/Zlink.Framework.csproj"/>
    </ItemGroup>
</Project>
