plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.netty:netty-all:4.1.108.Final'
}

application {
    mainClass = 'dev.kairoscode.stream.NettyStreamServer'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
}
