<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>LocationMessaging.Provider</AssemblyName>
        <RootNamespace>LocationMessaging.Provider</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../Shared/LocationMessaging.Shared.csproj"/>
        <ProjectReference Include="../../../../src/Zlink.Framework/Zlink.Framework.csproj"/>
        <ProjectReference Include="../../../../src/Zlink.Framework.AspNetCore/Zlink.Framework.AspNetCore.csproj"/>
        <ProjectReference Include="../../../../src/Zlink.Framework.Locations.Redis/Zlink.Framework.Locations.Redis.csproj"/>
    </ItemGroup>
</Project>
