include(CMakeFindDependencyMacro)
find_dependency(zlink CONFIG)
find_package(protobuf CONFIG QUIET)
if(NOT protobuf_FOUND)
  find_dependency(Protobuf)
endif()
find_dependency(Boost)
find_dependency(zlink_framework_cpp CONFIG)
find_dependency(zlink_http_client_cpp CONFIG)
find_dependency(zlink_stream_connector_cpp CONFIG)
