# SPDX-License-Identifier: MPL-2.0

"""Public Core contract surface of the zlink Python bindings.

Runtime factories live on the top-level :mod:`zlink` package. Framework-specific
concepts are outside this Core binding.
"""

from .core import (
    Context,
    ContextOptions,
    CoreHwmBudgetSnapshot,
    RoutingId,
    AtomicCounter,
    Stopwatch,
    Thread,
)
from .core.options import (
    ContextOption,
    AutoHwmProfile,
    AutoHwmRecalcReason,
)
from .sockets.codes import (
    SocketType,
    SendFlags,
    RecvFlags,
    SubmitResult,
    RequestResult,
    RecvResult,
    HandlerResult,
    RidDuplicatePolicy,
    SubmitRetryMode,
    ReceiveFlowState,
    StreamRecvMode,
)
from .errors.codes import (
    CloseResult,
    BindResult,
    ConnectResult,
    ConfigResult,
    ErrorCode,
    ProtocolError,
    DisconnectReason,
)
from .eventing.codes import (
    MonitorEventMask,
    MonitorEventFlag,
    MonitorStatusDetail,
    PollEventFlag,
    PollSourceKind,
)
from .errors import (
    ZlinkError,
    SubmitError,
    RequestError,
    RecvError,
    HandlerError,
    CloseError,
    BindError,
    ConnectError,
    ConfigError,
)
from .messaging import (
    Message,
    Received,
    TopicMessage,
    SubscriptionEvent,
    ReplyToken,
    StreamPacket,
)
from .eventing import (
    MonitorEvent,
    MonitorStatus,
    MonitorSocket,
    Poller,
    PollEvent,
    PollEvents,
    Timer,
)
from .sockets.operations import PublishOp, ReplyOp, RequestOp, SendOp
from .sockets import (
    CommonSocketOptions,
    DealerSocketOptions,
    StreamSocketOptions,
    SubSocketOptions,
    PubSocketOptions,
    RouterSocketOptions,
    PairSocket,
    DealerSocket,
    RouterSocket,
    StreamSocket,
    PubSocket,
    SubSocket,
    XPubSocket,
    XSubSocket,
)

__all__ = [
    "Context",
    "ContextOptions",
    "CoreHwmBudgetSnapshot",
    "RoutingId",
    "AtomicCounter",
    "Stopwatch",
    "Thread",
    "SocketType",
    "ContextOption",
    "AutoHwmProfile",
    "AutoHwmRecalcReason",
    "SendFlags",
    "RecvFlags",
    "SubmitResult",
    "RequestResult",
    "RecvResult",
    "HandlerResult",
    "CloseResult",
    "BindResult",
    "ConnectResult",
    "ConfigResult",
    "RidDuplicatePolicy",
    "SubmitRetryMode",
    "ReceiveFlowState",
    "StreamRecvMode",
    "ErrorCode",
    "ProtocolError",
    "MonitorEventMask",
    "MonitorEventFlag",
    "MonitorStatusDetail",
    "DisconnectReason",
    "PollEventFlag",
    "PollSourceKind",
    "ZlinkError",
    "SubmitError",
    "RequestError",
    "RecvError",
    "HandlerError",
    "CloseError",
    "BindError",
    "ConnectError",
    "ConfigError",
    "Message",
    "Received",
    "TopicMessage",
    "SubscriptionEvent",
    "ReplyToken",
    "StreamPacket",
    "SendOp",
    "PublishOp",
    "RequestOp",
    "ReplyOp",
    "MonitorEvent",
    "MonitorStatus",
    "MonitorSocket",
    "Poller",
    "PollEvent",
    "PollEvents",
    "Timer",
    "CommonSocketOptions",
    "DealerSocketOptions",
    "StreamSocketOptions",
    "SubSocketOptions",
    "PubSocketOptions",
    "RouterSocketOptions",
    "PairSocket",
    "DealerSocket",
    "RouterSocket",
    "StreamSocket",
    "PubSocket",
    "SubSocket",
    "XPubSocket",
    "XSubSocket",
]
